### ISSUE TITLE
To use the demo, it is required to use F12 to set the login prompt to "display:none".

### ISSUE THREAD

**Issue by e99243506bigplay** [codefuse-ai/codefuse#6] opened 2023-09-28 06:22 UTC
一上来登录要手机号的，其他模型Demo试用也不需要登录啊。例如Falcon 180B或者WizardLM模型都有自己的免登录Demo试用。

**Comment by ss41979310** [comment] 2023-10-08 11:57
给你带来不好的体验很抱歉。登陆要求是魔搭社区的默认设置。我们跟他们联系一下看是否能取消登陆要求限制。

**Comment by ss41979310** [comment] 2023-10-08 12:05
I apologize for the inconvenience caused by the requirement to log in. It is the default setting of the ModelScope Community. We have reached out to the ModelScope Community and the initial login is necessary to comply with government regulatory requirements.

**Comment by ss41979310** [comment] 2023-10-10 03:36
I will close this issue. You can reopen it if you have more questions. Thanks for your attention!

**Closed by ss41979310** 2023-10-10 03:36 UTC
